### ISSUE TITLE
Add metadata 

### ISSUE THREAD

**Issue by duerrsimon** [colab-db/colab-db.github.io#13]
In `pages/index.vue` one should load `metadata.json` and add a function that retrieves that information  in https://github.com/colab-db/colab-db.github.io/blob/main/pages/index.vue#L54 based on `b._path`

**Comment by duerrsimon** [comment]
@kjappelbaum lmk if you want to work on this

**Comment by kjappelbaum** [comment]
Yes, I can give it a shot, but will only get to it next week I think

**Comment by duerrsimon** [comment]
Almost completed  this now. Will need to add comments (likely will do tomorrow)
